title: Data Model
tooltip: description
shapes:
  source: cds
  seed: component
  model: box
palette: Pastel
fontcolor: black
clusters:
  staging:
    subgraph: true
    rank: true
  seed:
    subgraph: false
    rank: false
  root:
    subgraph: false
    rank: false